name: intranet
recipe: drupal8
config:
  webroot: web
  via: nginx
  php: '7.3'
services:
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
  database:
    type: mariadb:10.2
    portforward: true
  migrationdb:
    type: mariadb:10.2
    portforward: true
    creds:
      user: migration
      password: migration
      database: migration
  redis:
    type: redis
    persist: true
tooling:
  drush:
    cmd: /app/vendor/drush/drush/drush --root=/app
  phpcs:
    description: Run PHP Code Sniffer
    service: appserver
    cmd: /app/bin/phpcs
  phpcbf:
    description: Run PHP Code Beautifier and Fixer (automatically fix CS)
    service: appserver
    cmd: /app/bin/phpcbf
  redis-cli:
    service: redis